### PR TITLE
WIP #291 better decimal in dbr

### PR DESCRIPTION
**Pull request by kristianschneider**
Support larger precision in data bricks decimals

### CODE REVIEW

**Comment by kristianschneider** [comment]
Should we perhaps bump the general runtime in both dev and in the cluster infrastructure up ?
https://docs.databricks.com/release-notes/runtime/releases.html

Right now we are on a LTS version 7.3 with spark 3.0.1 that has a EOS next year

**Comment by ZavezX** [comment]
> Should we perhaps bump the general runtime in both dev and in the cluster infrastructure up ?
> https://docs.databricks.com/release-notes/runtime/releases.html
> 
> Right now we are on a LTS version 7.3 with spark 3.0.1 that has a EOS next year

LTS 7.3 has the longest lifetime of all the versions available right now, maybe we should wait until a new LTS version becomes available?

**Comment by ZavezX** [comment]
Only merge this after #296 is merged.

**Comment by mknic** [comment]
> Should we perhaps bump the general runtime in both dev and in the cluster infrastructure up ?
> https://docs.databricks.com/release-notes/runtime/releases.html
> 
> Right now we are on a LTS version 7.3 with spark 3.0.1 that has a EOS next year

Actually, the 7.3 LTS we are using expires late 2022 where version 8 and up expires before that date. 

This is an issue we will face in both `timeseries` and `aggregation` and I would prefer some kind of strategy on how to follow along new versions of databricks runtime, spark, python etc.?

@Sondergaard @MartinFHansen should we consider making an upgrade strategy for the databricks areas as we have with our .net applications?

**Comment by Sondergaard** [comment]
> > Should we perhaps bump the general runtime in both dev and in the cluster infrastructure up ?
> > https://docs.databricks.com/release-notes/runtime/releases.html
> > Right now we are on a LTS version 7.3 with spark 3.0.1 that has a EOS next year
> 
> Actually, the 7.3 LTS we are using expires late 2022 where version 8 and up expires before that date.
> 
> This is an issue we will face in both `timeseries` and `aggregation` and I would prefer some kind of strategy on how to follow along new versions of databricks runtime, spark, python etc.?
> 
> @Sondergaard @MartinFHansen should we consider making an upgrade strategy for the databricks areas as we have with our .net applications?

We need to consider how and when to upgrade - I don't think it should be a part of this PR. 
Can you create an issue with that subject and let's continue there.

**Comment by mknic** [comment]
#300

**Comment by mknic** [comment]
> > > Should we perhaps bump the general runtime in both dev and in the cluster infrastructure up ?
> > > https://docs.databricks.com/release-notes/runtime/releases.html
> > > Right now we are on a LTS version 7.3 with spark 3.0.1 that has a EOS next year
> > 
> > 
> > Actually, the 7.3 LTS we are using expires late 2022 where version 8 and up expires before that date.
> > This is an issue we will face in both `timeseries` and `aggregation` and I would prefer some kind of strategy on how to follow along new versions of databricks runtime, spark, python etc.?
> > @Sondergaard @MartinFHansen should we consider making an upgrade strategy for the databricks areas as we have with our .net applications?
> 
> We need to consider how and when to upgrade - I don't think it should be a part of this PR.
> Can you create an issue with that subject and let's continue there.

@Sondergaard I've created #300 for the purpose of this discussion and will invite members from Team Volt to take part in it as well.

**Comment by mknic** [comment]
Why was this closed @kristianschneider?

**Pull request closed without merging**
